Add hopannotation1 to paris traceroute
m-lab/etl pull request #1047
Opened 2022-01-27 03:12 UTC by cristinaleonr

2022-01-27 18:29 UTC, stephen-soltesz requested changes
Thank you for these changes.

I think the paris1 hopid construction is incorrect, please see the linked doc.

If the filename timestamp is all we have, then that's the right thing. These paris1 hopids only needs the date portion.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1047#-:-MuRm7v34j0sIpXyH6B4:b-8mdm3a)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[parser/pt.go, line 404 at r2](https://reviewable.io/reviews/m-lab/etl/1047#-MuRlvpP8sS_C6PCHmq1:-MuRlvpP8sS_C6PCHmq2:b-ron3pv) ([raw file](https://github.com/m-lab/etl/blob/c8a98162611baf6c06794f76ee8f217a4765aeb5/parser/pt.go#L404)):*
> ```Go
> 			}
> 			// For hopannotation1 hopIDs, the formatting convention is
> 			// Timestamp_IP_Hostname. However, the Hops initialized above
> ```

This description does not match my understanding from the TRC hopid convention. Can you confirm?
___
*[parser/pt.go, line 409 at r2](https://reviewable.io/reviews/m-lab/etl/1047#-MuRlTj_4hBPO6wEa4nN:-MuRlTj_4hBPO6wEa4nO:b-i3tuld) ([raw file](https://github.com/m-lab/etl/blob/c8a98162611baf6c06794f76ee8f217a4765aeb5/parser/pt.go#L409)):*
> ```Go
> 			// The same convention will have to be adopted in the paris1
> 			// parser, so its hops can be joined with the synthetic ones.
> 			hopID := GetHopID(float64(logTime.UTC().Unix()), source.IP, source.IP)
> ```

`source.IP`, `source.IP` does not look correct, please see comment below.
___
*[parser/pt.go, line 425 at r2](https://reviewable.io/reviews/m-lab/etl/1047#-MuRlEct18wqyvl6yPsu:-MuRlEcu38PRMsuhCn4z:b-cpys1v) ([raw file](https://github.com/m-lab/etl/blob/c8a98162611baf6c06794f76ee8f217a4765aeb5/parser/pt.go#L425)):*
> ```Go
> 				Hostname: allNodes[i].parent_hostname,
> 			}
> 			hopID := GetHopID(float64(logTime.UTC().Unix()), source.Hostname, source.IP)
> ```

Are these the correct three fields composing the hop id from traceroute-caller? 
https://docs.google.com/document/d/1VD5t4zRFlYsq_CAH6oCfjynKaEDnpwHnnFbk2mL7_yI/edit?resourcekey=0-NpaXaG91iS8nb02o9fqgbQ#heading=h.mzu1y33z63fh

Also, FYI: @saiedkazemi (I don't want to miss anything)
___
*[parser/pt_test.go, line 367 at r2](https://reviewable.io/reviews/m-lab/etl/1047#-MuRljyL121XqDwQMaea:-MuRljyL121XqDwQMaeb:b5sejm4) ([raw file](https://github.com/m-lab/etl/blob/c8a98162611baf6c06794f76ee8f217a4765aeb5/parser/pt_test.go#L367)):*
> ```Go
> 			Hostname:    "sr05-te1-8.nuq04.net.google.com",
> 			HopAnnotation1: &hopannotation.HopAnnotation1{
> 				ID:        "20170320_sr05-te1-8.nuq04.net.google.com_64.233.174.109",
> ```

Please confirm the hop id is correct.


<!-- Sent from Reviewable.io -->

2022-01-31 20:33 UTC, SaiedKazemi commented
___
*[parser/pt.go, line 425 at r2](https://reviewable.io/reviews/m-lab/etl/1047#-MuRlEct18wqyvl6yPsu:-MulpNv7Blz9LLeaNI86:b-sypa4x) ([raw file](https://github.com/m-lab/etl/blob/c8a98162611baf6c06794f76ee8f217a4765aeb5/parser/pt.go#L425)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are these the correct three fields composing the hop id from traceroute-caller? 
https://docs.google.com/document/d/1VD5t4zRFlYsq_CAH6oCfjynKaEDnpwHnnFbk2mL7_yI/edit?resourcekey=0-NpaXaG91iS8nb02o9fqgbQ#heading=h.mzu1y33z63fh

Also, FYI: @saiedkazemi (I don't want to miss anything)
</blockquote></details>

Looks good to me.  Here's what the doc says:

```
The hop annotation file name should consist of the following three fields concatenated with an underscore character (_) and followed by a .json suffix:

  1. Timestamp - This should be the timestamp when traceroute ran (see Hop Annotation File Content for more details).
  2. Hostname - This should be the hostname where TRC is running on.
  3. IP address - This should be the IP address of the hop that is annotated.
```


<!-- Sent from Reviewable.io -->

2022-01-31 20:40 UTC, stephen-soltesz reviewed
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1047)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @SaiedKazemi)

___
*[parser/pt.go, line 425 at r2](https://reviewable.io/reviews/m-lab/etl/1047#-MuRlEct18wqyvl6yPsu:-Mulr6WL2KrbIaelqzOl:b-8fz91g) ([raw file](https://github.com/m-lab/etl/blob/c8a98162611baf6c06794f76ee8f217a4765aeb5/parser/pt.go#L425)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Looks good to me.  Here's what the doc says:

```
The hop annotation file name should consist of the following three fields concatenated with an underscore character (_) and followed by a .json suffix:

  1. Timestamp - This should be the timestamp when traceroute ran (see Hop Annotation File Content for more details).
  2. Hostname - This should be the hostname where TRC is running on.
  3. IP address - This should be the IP address of the hop that is annotated.
```

</blockquote></details>

@saiedkazemi should the `Hostname` be that of the M-Lab server or the reverse-lookup hostname of the hop router? Which is being used here?


<!-- Sent from Reviewable.io -->

2022-02-01 00:00 UTC, SaiedKazemi commented
___
*[parser/pt.go, line 425 at r2](https://reviewable.io/reviews/m-lab/etl/1047#-MuRlEct18wqyvl6yPsu:-MumZpyD4CWLgRBDqtqe:b-ycdark) ([raw file](https://github.com/m-lab/etl/blob/c8a98162611baf6c06794f76ee8f217a4765aeb5/parser/pt.go#L425)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

@saiedkazemi should the `Hostname` be that of the M-Lab server or the reverse-lookup hostname of the hop router? Which is being used here?
</blockquote></details>

@stephen-soltesz Per our offline conversation, the hostname in the screenshot `ge-11-0-2...` is not what we want.  I will set up a meeting with @cristinaleonr to discuss this.


<!-- Sent from Reviewable.io -->

2022-02-02 12:56 UTC, cristinaleonr reviewed
Updated the hopid to use the M-Lab server's `Hostname`.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1047#-:-MuuVAKNAAshXefT2SVE:b4st1ej)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)



<!-- Sent from Reviewable.io -->

2022-02-02 19:07 UTC, cristinaleonr reviewed
Updated, thanks!

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1047#-:-MuvpFLD4CpyFFw0ADZF:b94jzny)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr and @stephen-soltesz)

___
*[parser/pt.go, line 925 at r5](https://reviewable.io/reviews/m-lab/etl/1047#-MuvFYfdAFR2qE_xpz0U:-MuvpMDe-42q4p2lOV5X:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ff22adba20702e97a63c314d7ad79c75570486d1/parser/pt.go#L925)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Since the dual use of "hostname" was the source of some of the ambiguity, what do you think of calling this the "machine" throughout instead?
</blockquote></details>

Done.
___
*[parser/pt.go, line 925 at r5](https://reviewable.io/reviews/m-lab/etl/1047#-MuvGwjo79AvhCrujth-:-MuvpPNuEc1piH6pg2TX:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/ff22adba20702e97a63c314d7ad79c75570486d1/parser/pt.go#L925)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Rather than reparsing the archive url, consider reusing the `DataPath` type returned by `etl.ValidateTestPath` from the logic where `Parse()` is called.

The DataPath type has fields for the "Host" and "Site" which together create the machine name.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-02 20:11 UTC, stephen-soltesz requested changes
Bonus points for updating the screenshot. (and thank you! -- it can be very confusing looking back and PRs when the original description becomes out of sync with what was actually done).

Just to confirm, the HopAnnotations1 are now being populated? Is it the case that previously that `PTTest.AnnotateHops()` wasn't filling them in b/c the structs were `nil`?

I think this will lgtm with confirmation.

> Reviewed 2 of 3 files at r6, 1 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1047#-:-Muw0m5C6LHHG7glqFHC:b79ukuc)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @cristinaleonr)

___
*[parser/pt.go, line 403 at r7](https://reviewable.io/reviews/m-lab/etl/1047#-Muw2ana3emmXVEJaQ4I:-Muw2ana3emmXVEJaQ4J:bq510j8) ([raw file](https://github.com/m-lab/etl/blob/c46aadeff0db8882759fb471b617be89a5c10102/parser/pt.go#L403)):*
> ```Go
> 				IP: server_IP,
> 			}
> 			hopID := GetHopID(float64(logTime.UTC().Unix()), machine, source.IP)
> ```

These lines look identical here and below.

Is it possible/preferable to eliminate the redundancy?



_Code quote:_
```Go
			hopID := GetHopID(float64(logTime.UTC().Unix()), machine, source.IP)
			source.HopAnnotation1 = &hopannotation.HopAnnotation1{
				ID:        hopID,
				Timestamp: logTime,
			}
```


<!-- Sent from Reviewable.io -->

2022-02-02 23:40 UTC, cristinaleonr reviewed
Yes, the `HopAnnotations` are being populated for `paris-traceroute` now. And yes, before they weren't before the structs were `nil` for pt.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1047#-:-MuwnPai6oSSPDeJTMWK:bucm7d4)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[parser/pt.go, line 403 at r7](https://reviewable.io/reviews/m-lab/etl/1047#-Muw2ana3emmXVEJaQ4I:-MuwnMCm9Ep2psSXWgvM:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/c46aadeff0db8882759fb471b617be89a5c10102/parser/pt.go#L403)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

These lines look identical here and below.

Is it possible/preferable to eliminate the redundancy?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-03 00:30 UTC, stephen-soltesz approved these changes
This <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> - thank you.. DO NOT MERGE YET.

I setup a time for you, @robertodauria and I to talk tomorrow morning (hopefully) to sort out the order of events necessary to minimize headache for getting this into production without breaking anything else and setting us up for decoupling the v1/v2 deployments.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/1047#-:-MuwywIsAQraIqhv0K8Y:b-sxaz7e)* status: :shipit: complete! 1 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2022-02-03 20:51 UTC, merged

2022-02-04 15:32 UTC, stephen-soltesz commented
Part of https://github.com/m-lab/etl/issues/1050