Add NDTWeb100 struct to mirror current BQ schema
m-lab/etl pull request #988
Opened 2021-04-15 21:52 UTC by stephen-soltesz

This change adds a new Go struct that mirrors the current ndt web100 schema.

Notable differences:

* `Deltas` reuses the `web100Snap` structure, which includes LocalAddress, RemAddress, and related fields that are not found in the current schema. This difference simplifies the structure without duplicating all other fields.
* Adding `api.ASData` to the client and server network information to mirror annotation-service values.
* Adding `api.GeolocationIP` for the client and server geolocation to mirror annotation-service values.
* Server geolocation does not include "Machine" and "Site" fields used in the uuid-annotator.

I accidentally updated part of the `mlab-sandbox.base_tables.ndt` table during testing of `update-schema` so the extra columns noted above are already present in the sandbox tables.

To compare this and production schemas:

```
$ bq show --format=prettyjson mlab-sandbox:base_tables.ndt | jq .schema.fields > new.schema
$ bq show --format=prettyjson mlab-oti:base_tables.ndt | jq .schema.fields > orig.schema
$ diff -Ndur <( sort orig.schema ) <( sort new.schema ) | less
```

2021-04-16 14:07 UTC, gfr10598 reviewed
> diff -Ndur <( sort orig.schema ) <( sort new.schema ) | less
Suggest a little explanation on how to interpret the diff.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MYQ-SDt8z4bbe4TSRrR:b37frkr)* status: 0 of 1 approvals obtained



<!-- Sent from Reviewable.io -->

2021-04-16 14:11 UTC, gfr10598 reviewed
Wow that was fast - looks great on quick perusal.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MYQ0Kan-5boeD4IHinI:b-mbl0gg)* status: 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[schema/ndt_web100.go, line 15 at r1](https://reviewable.io/reviews/m-lab/etl/988#-MYQ-i9o2zGGSfiVysY3:-MYQ-i9o2zGGSfiVysY4:b-g2oeb6) ([raw file](https://github.com/m-lab/etl/blob/77dee650d09a083b57d644114547dfbcd879725a/schema/ndt_web100.go#L15)):*
> ```Go
> // WARNING // WARNING // WARNING
> //
> // TODO: migrate parser/ndt.go to use native struct AFTER standard column migration.
> ```

I was thinking we could migrate to use the struct first, then standard columns, then G2.0


<!-- Sent from Reviewable.io -->

2021-04-20 16:37 UTC, stephen-soltesz commented
@gfr10598 PTAL?

2021-04-26 15:49 UTC, gfr10598 commented
Better diff
bq show --format=prettyjson mlab-sandbox:base_tables.ndt | jq -c .schema.fields | sed "s/},/},\n/g" > new.schema
bq show --format=prettyjson mlab-oti:base_tables.ndt | jq -c .schema.fields | sed "s/},/},\n/g" > orig.schema
diff -Ndur <( sort orig.schema ) <( sort new.schema ) | less

2021-04-26 20:12 UTC, gfr10598 requested changes
Actually, the diff works pretty well without the sort, too.

There is stuff in the sandbox table that is no longer in struct.  Systems, ASNs, IPPrefix, all seem to be in the sandbox table, but not in this schema.  Suggest we delete that table and recreate it, so we can do the comparison more directly.

{"fields":[{"name":"iata_code","type":"STRING"},
{"fields":[{"name":"asn","type":"STRING"}],
"name":"network","type":"RECORD"},
{"name":"IPPrefix","type":"STRING"},
{"fields":[{"mode":"REPEATED","name":"ASNs","type":"INTEGER"}],
"mode":"REPEATED","name":"Systems","type":"RECORD"}],

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MZElwwZ4sU18nsIkJsa:b-f8s2vk)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[schema/ndt_web100.go, line 20 at r2](https://reviewable.io/reviews/m-lab/etl/988#-MZElmEiEQIcW5JilL_2:-MZElmEiEQIcW5JilL_3:b-ewu68e) ([raw file](https://github.com/m-lab/etl/blob/d544397cf7cfa2d5e4cad079ead253d62efb1f3a/schema/ndt_web100.go#L20)):*
> ```Go
> 	TaskFilename   string                  `bigquery:"task_filename"`
> 	ParseTime      time.Time               `bigquery:"parse_time"`
> 	ParserVersion  string                  `bigquery:"parser_version"`
> ```

parser_version is relocated in the sandbox table, but I assume that is from a previous version.
___
*[schema/ndt_web100.go, line 120 at r2](https://reviewable.io/reviews/m-lab/etl/988#-MZEmlGZ56IRFUtdPXWl:-MZEmlGZ56IRFUtdPXWm:bkyxlb4) ([raw file](https://github.com/m-lab/etl/blob/d544397cf7cfa2d5e4cad079ead253d62efb1f3a/schema/ndt_web100.go#L120)):*
> ```Go
> 	LimCwnd              int64
> 	LimRwin              int64
> 	LocalAddress         string
> ```

These are all added?
{"name":"LocalAddress","type":"STRING"},
{"name":"LocalAddressType","type":"INTEGER"},
{"name":"LocalPort","type":"INTEGER"},
{"name":"RemAddress","type":"STRING"},
{"name":"RemPort","type":"INTEGER"},


<!-- Sent from Reviewable.io -->

2021-04-26 21:46 UTC, stephen-soltesz reviewed
I've recreated the sandbox `batch.ndt` and `base_tables.ndt` tables.

I've updated the delta struct definition to eliminate the `Local*` & `Rem*` fields that were previously absent from the deltas record by creating a separate struct, but using embedding to minimize redundancy.

The `IPPrefix` and `ASNs` `Systems` fields came from using the annotation-service `api.ASData` records, which were previously not present. But, I'm violating the rule of doing more than one thing in a PR. So, I've commented those fields out.

The remaining columns are 1:1 with one exception: the `SACK` field in the deltas struct is the only new field there. Do you recall why that was left out of the deltas struct originally? It would be convenient to leave it there if possible.

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MZF2BQV6LrxEm0l9P5N:b4hbcc5)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)

___
*[schema/ndt_web100.go, line 15 at r1](https://reviewable.io/reviews/m-lab/etl/988#-MYQ-i9o2zGGSfiVysY3:-MYk7hOd9g7WYe1A8xS9:bv5wtlc) ([raw file](https://github.com/m-lab/etl/blob/77dee650d09a083b57d644114547dfbcd879725a/schema/ndt_web100.go#L15)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

I was thinking we could migrate to use the struct first, then standard columns, then G2.0
</blockquote></details>

Ack updated comment.
___
*[schema/ndt_web100.go, line 20 at r2](https://reviewable.io/reviews/m-lab/etl/988#-MZElmEiEQIcW5JilL_2:-MZF7yUUBhIXHxvDillv:b7bzujb) ([raw file](https://github.com/m-lab/etl/blob/d544397cf7cfa2d5e4cad079ead253d62efb1f3a/schema/ndt_web100.go#L20)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

parser_version is relocated in the sandbox table, but I assume that is from a previous version.
</blockquote></details>

I think it was at the end of the schema in the original b/c we added it after the fact.
___
*[schema/ndt_web100.go, line 120 at r2](https://reviewable.io/reviews/m-lab/etl/988#-MZEmlGZ56IRFUtdPXWl:-MZEukGH8kczsjSeaXtB:b-o9tugt) ([raw file](https://github.com/m-lab/etl/blob/d544397cf7cfa2d5e4cad079ead253d62efb1f3a/schema/ndt_web100.go#L120)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

These are all added?
{"name":"LocalAddress","type":"STRING"},
{"name":"LocalAddressType","type":"INTEGER"},
{"name":"LocalPort","type":"INTEGER"},
{"name":"RemAddress","type":"STRING"},
{"name":"RemPort","type":"INTEGER"},
</blockquote></details>

Yes, it's a result of reusing the  `web100Snap` struct for the `deltas` record without duplicating the struct. I've tried doing it the other way around to keep these out of the delta records, and inhering from the delta struct in the 'snap' struct.


<!-- Sent from Reviewable.io -->

2021-04-26 21:46 UTC, stephen-soltesz reviewed
PTAL?

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MZF8Wfz3j5mvspCpUTA:b-833305)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @gfr10598)



<!-- Sent from Reviewable.io -->

2021-04-28 13:48 UTC, gfr10598 requested changes
I don't recall, and SACK is pretty important, too.  So good to have it there.

I think this also properly filters out the descriptions:
diff -Ndur <( sed "s/\"description[^,]*\",//" orig.schema | sort ) <( sort new.schema ) | less

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MZNeMW6BnYrIYajcKa3:bcob3v8)* status: 1 change requests, 0 of 1 approvals obtained (waiting on @stephen-soltesz)

___
*[schema/ndt_web100.go, line 28 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNj6KE1ie3u-IFK8oU:-MZNj6KE1ie3u-IFK8oV:bv6tlrt) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L28)):*
> ```Go
> }
> 
> type ndtweb100Anomalies struct {
> ```

Here and elsewhere, just use ndtAnomalies, ndtConnectionSpec, etc. ??
___
*[schema/ndt_web100.go, line 61 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNit4n3wGVSrjwvGcC:-MZNit4n3wGVSrjwvGcD:b-o58h7h) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L61)):*
> ```Go
> }
> 
> type ndtweb100ClientNetwork struct {
> ```

maybe just ndtClientNetwork?
___
*[schema/ndt_web100.go, line 65 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNiw7t3OZUaAVYBLeq:-MZNiw7t3OZUaAVYBLer:b-tv9w1p) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L65)):*
> ```Go
> 	// api.ASData         // Include extended asn data from  annotation-service
> }
> type ndtweb100ServerNetwork struct {
> ```

Just ndtServerNetwork?
___
*[schema/ndt_web100.go, line 212 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNi_M60p4-oUFXRfyx:-MZNi_M60p4-oUFXRfyy:b-83sjoh) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L212)):*
> ```Go
> 	SnapshotNum     int64 `bigquery:"snapshot_num"`
> 	DeltaIndex      int64 `bigquery:"delta_index"`
> 	web100SnapDelta       // embed inline struct.
> ```

Nice!


<!-- Sent from Reviewable.io -->

2021-04-28 13:50 UTC, gfr10598 approved these changes
After resolving comments, <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MZNjaBf1VfUw4ZdGvwd:b-k3p2ok)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @stephen-soltesz)



<!-- Sent from Reviewable.io -->

2021-04-28 14:48 UTC, stephen-soltesz reviewed
Thank you!

> *[Reviewable](https://reviewable.io/reviews/m-lab/etl/988#-:-MZNx0qzBRZEOYCIIDLz:b-9755fn)* status: :shipit: complete! 1 of 1 approvals obtained (waiting on @gfr10598)

___
*[schema/ndt_web100.go, line 28 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNj6KE1ie3u-IFK8oU:-MZNwVYKDaKUgEmUaf_2:b8i0p0c) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L28)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Here and elsewhere, just use ndtAnomalies, ndtConnectionSpec, etc. ??
</blockquote></details>

I did this b/c of the experiment/datatype name. But, as long as these types/names remain package private, it should be okay.
___
*[schema/ndt_web100.go, line 61 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNit4n3wGVSrjwvGcC:-MZNwayn7SWADpX3qBdk:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L61)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

maybe just ndtClientNetwork?
</blockquote></details>

Done.
___
*[schema/ndt_web100.go, line 65 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNiw7t3OZUaAVYBLeq:-MZNwbp18IjGECy2HkRt:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L65)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Just ndtServerNetwork?
</blockquote></details>

Done.
___
*[schema/ndt_web100.go, line 212 at r3](https://reviewable.io/reviews/m-lab/etl/988#-MZNi_M60p4-oUFXRfyx:-MZNwf0tCiA7EfHfMkj2:b-896fix) ([raw file](https://github.com/m-lab/etl/blob/b93ed0653489f52ba2fe1f181c4bd2c61ac64997/schema/ndt_web100.go#L212)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-28 15:10 UTC, merged